version: '2'
services:
  nodejs:
    build: nodejs
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "server.js"]
  mysql:
    build: mysql
    environment:
      MYSQL_DATABASE: geoquality
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 127.0.0.1
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    ports:
      - "3306:3306"
